replicaCount: 3

image:
  repository: rabbitmq
  tag: "3.12-management"
  pullPolicy: IfNotPresent

serviceAccount:
  create: false  # Disable service account creation

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  storageClass: "standard"

rabbitmq:
  erlangCookie: my-erlang-cookie
  defaultUser: admin
  defaultPass: password@123
  useLongName: true
  nodes:
    - rabbit@rabbitmq-0.rabbitmq.rabbit.svc.cluster.local
    - rabbit@rabbitmq-1.rabbitmq.rabbit.svc.cluster.local
    - rabbit@rabbitmq-2.rabbitmq.rabbit.svc.cluster.local

auth:
  username: admin
  password: cGFzc3dvcmRAMTIz  
