apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.auth.username | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.auth.password | b64enc | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.auth.erlangCookie | b64enc | quote }}
