apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  erlangCookie: {{ .Values.auth.erlangCookie | b64enc | quote }}
