apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth
type: Opaque
data:
  username: {{ .Values.auth.username | default "defaultUser" | b64enc | quote }}
  password: {{ .Values.auth.password | default "defaultPassword" | b64enc | quote }}
  erlangCookie: {{ .Values.auth.erlangCookie | default "defaultErlangCookie" | b64enc | quote }}
