apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      initContainers:
        - name: rabbitmq-peer-discovery
          image: busybox
          command: ['sh', '-c', 'echo waiting for cluster setup...; sleep 10']
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "{{ .Values.auth.erlangCookie }}"
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.auth.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.auth.password }}"
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(HOSTNAME).rabbitmq.default.svc.cluster.local"
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
