apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: rabbit
  labels:
    app: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      initContainers:
        - name: rabbitmq-peer-discovery
          image: busybox
          command:
            - sh
            - -c
            - echo waiting for cluster setup...; sleep 10
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "{{ .Values.rabbitmq.erlangCookie }}"
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmq.defaultUser }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.rabbitmq.defaultPass }}"
            - name: RABBITMQ_NODENAME
              value: rabbit@$(HOSTNAME).rabbitmq.rabbit.svc.cluster.local
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 8Gi
